// ts/svelte/free2z/src/lib/components/AudioVisualizerCanvas.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';

    export let analyser: AnalyserNode | null = null;
    export let dataArray: Uint8Array | null = null;

    let canvas: HTMLCanvasElement;
    let ctx: CanvasRenderingContext2D | null = null;
    let animationFrameId: number;
    let resizeObserver: ResizeObserver;
    let binMapping: number[] = [];
    let currentSampleRate: number = 0;

    const FFT_SIZE = 1024;
    const NUM_BARS = 128;
    const AMPLITUDE_NORMALIZER = 256.0;
    const MAX_BAR_WIDTH_RATIO = 0.8;
    const BASE_BAR_WIDTH = 2;
    const BAR_SPACING = 1;
    const MIN_FREQUENCY_HZ = 22.5;
    
    
    function mapAmplitudeToColor(amplitude: number): string {
        // Interpolating the hue value from blue (240) to red (0)
        const hue = 240 - (amplitude * 240);
        return `hsl(${hue}, 100%, 50%)`;
    }

    function calculateBinMapping(sampleRate: number) {
        if (sampleRate === currentSampleRate && binMapping.length === NUM_BARS) return;
        
        currentSampleRate = sampleRate;
        binMapping = new Array(NUM_BARS);
        
        const minHz = MIN_FREQUENCY_HZ;
        const maxHz = sampleRate / 2;
        const binSize = sampleRate / FFT_SIZE;

        for (let i = 0; i < NUM_BARS; i++) {
            const indexNormalized = i / NUM_BARS;
            // Using a logarithmic scale to allocate more bars to lower frequencies
            const exponent = (Math.log(maxHz / minHz) * indexNormalized);
            const freq = minHz * Math.exp(exponent);
            
            const bin = Math.floor(freq / binSize);
            binMapping[i] = Math.min(Math.max(bin, 0), (FFT_SIZE / 2) - 1);
        }
    }

    function draw() {
        if (!canvas || !ctx || !analyser) return;

        // Auto-initialize dataArray if needed
        if (!dataArray) {
            dataArray = new Uint8Array(analyser.frequencyBinCount);
        }

        // Get audio data
        if (dataArray) {
            analyser.getByteFrequencyData(dataArray as any);
        }
        
        const sampleRate = analyser.context.sampleRate;
        
        if (sampleRate !== currentSampleRate) {
            calculateBinMapping(sampleRate);
        }

        const width = canvas.width / (window.devicePixelRatio || 1);
        const height = canvas.height / (window.devicePixelRatio || 1);
        ctx.clearRect(0, 0, width, height);

        const barHeight = height / NUM_BARS;
        const centerX = width / 2;
        const maxBarWidth = width * MAX_BAR_WIDTH_RATIO;

        for (let i = 0; i < NUM_BARS; i++) {
            const binIndex = binMapping[i];
            const amplitude = dataArray[binIndex] || 0;
            const normalizedAmplitude = amplitude / AMPLITUDE_NORMALIZER;
            const barWidth = (normalizedAmplitude * maxBarWidth) + BASE_BAR_WIDTH;
            
            const color = mapAmplitudeToColor(normalizedAmplitude);
        
            const y = height - (i * barHeight) - barHeight;

            ctx.fillStyle = color;
            
            
            ctx.beginPath();
            // Draw a rounded rectangle or ellipse to look like a disc viewed from side
            // Simple rect for now as requested "bars"
            ctx.fillRect(centerX - (barWidth / 2), y, barWidth, barHeight - BAR_SPACING);
        }

        animationFrameId = requestAnimationFrame(draw);
    }

    function handleResize() {
        if (canvas && canvas.parentElement) {
            const parent = canvas.parentElement;
            const dpr = window.devicePixelRatio || 1;
            
            canvas.width = parent.clientWidth * dpr;
            canvas.height = parent.clientHeight * dpr;
            
            if (ctx) {
                ctx.setTransform(1, 0, 0, 1, 0, 0);
                ctx.scale(dpr, dpr);
            }
        }
    }

    function requestFullScreen() {
        if (canvas && canvas.requestFullscreen) {
            canvas.requestFullscreen();
        }
    }

    onMount(() => {
        if (canvas) {
            ctx = canvas.getContext('2d');
            
            handleResize();

            resizeObserver = new ResizeObserver(handleResize);
            if (canvas.parentElement) {
                resizeObserver.observe(canvas.parentElement);
            }

            draw();
        }
    });

    onDestroy(() => {
        if (animationFrameId) {
            cancelAnimationFrame(animationFrameId);
        }
        if (resizeObserver) {
            resizeObserver.disconnect();
        }
    });
</script>

<canvas 
    bind:this={canvas}
    class="w-full h-full block cursor-pointer"
    style="background: transparent;"
    on:click={requestFullScreen}
></canvas>

// ts/react/free2z/src/components/AudioVisualizerCanvas.tsx
import React, { useRef, useEffect, useState } from 'react';
import { Canvas } from '@react-three/fiber';
import { Mesh } from 'three';
import RotatingCamera from './RotatingCamera';

const FFT_SIZE = 1024;

// Visualization constants
const Y_OFFSET = 0.25;
const NUM_BARS = 128;
const BAR_WIDTH = 0.001;
const BAR_HEIGHT = 0.05;
// const BAR_DEPTH = 0.001;
const BAR_SPACING = 0.0001;
const MAX_SCALE = 3500;
const AMPLITUDE_NORMALIZER = 256.0; // Normalizes the amplitude values
const HALF_BARS = NUM_BARS / 2;

type VisualizerProps = {
    dataArrayRef: React.RefObject<Uint8Array>;
    analyserRef: React.RefObject<AnalyserNode>;
};

const mapAmplitudeToColor = (amplitude: number): string => {
    // Interpolating the hue value from blue (240) to red (0)
    const hue = 240 - (amplitude * 240);
    return `hsl(${hue}, 100%, 50%)`;
};


const Bar: React.FC<{
    position: [number, number, number],
    scale: [number, number, number],
    color: string,
}> = ({ position, scale, color }) => {
    const meshRef = useRef<Mesh>(null);
    const borderMeshRef = useRef<Mesh>(null);

    useEffect(() => {
        if (meshRef.current && borderMeshRef.current) {
            meshRef.current.scale.set(scale[0], scale[1], scale[2]);
            borderMeshRef.current.scale.set(scale[0] * 1.01, scale[1] * 1.01, scale[2] * 1.01);
        }
    }, [scale]);

    return (
        <>
            {/* https://threejs.org/docs/#api/en/geometries/CylinderGeometry */}
            <mesh ref={borderMeshRef} position={position}>
                <cylinderBufferGeometry args={[BAR_WIDTH * 1.05, BAR_WIDTH * 1.05, BAR_HEIGHT * 1.05, 32]} />
                <meshStandardMaterial color={'black'} transparent opacity={0.15} />
            </mesh>
            <mesh ref={meshRef} position={position}>
                <cylinderBufferGeometry args={[BAR_WIDTH, BAR_WIDTH, BAR_HEIGHT, 32]} />
                <meshStandardMaterial color={color} />
            </mesh>
        </>
    );
};


const AudioVisualizerCanvas: React.FC<VisualizerProps> = ({ dataArrayRef, analyserRef }) => {
    const [bars, setBars] = useState<Array<{
        scale: [number, number, number],
        color: string,
    }>>(Array(NUM_BARS).fill({
        scale: [1, 1, 1],
        color: 'hsl(0, 100%, 50%)',
    }));

    const animateRAF = useRef<number>(0);

    const mapBarToFrequencyBin = (index: number, totalBars: number, sampleRate: number) => {
        const minHz = 22.5;
        const maxHz = sampleRate;
        const indexNormalized = index / totalBars;

        // Using a logarithmic scale to allocate more bars to lower frequencies
        const exponent = (Math.log(maxHz / minHz) * indexNormalized);
        const freq = minHz * Math.exp(exponent);
        const bin = Math.floor(freq / sampleRate * FFT_SIZE);

        return bin;
    };

    const animate = () => {
        if (analyserRef.current && dataArrayRef.current) {
            analyserRef.current.getByteFrequencyData(dataArrayRef.current);
            const sampleRate = analyserRef.current.context.sampleRate;
            const newScales = Array.from({ length: NUM_BARS }, (_, index) => {
                const binIndex = mapBarToFrequencyBin(index, NUM_BARS, sampleRate);
                const amplitude = dataArrayRef.current ? dataArrayRef.current[binIndex] : 0;
                const normalizedAmplitude = amplitude / AMPLITUDE_NORMALIZER;
                const scale = normalizedAmplitude * MAX_SCALE;
                const color = mapAmplitudeToColor(normalizedAmplitude);
                return { scale: [scale, 1, scale] as [number, number, number], color };
            });
            setBars(newScales);
        }
        animateRAF.current = requestAnimationFrame(animate);
    };

    useEffect(() => {
        animate();
        return () => {
            if (animateRAF.current) {
                cancelAnimationFrame(animateRAF.current);
            }
        };
    }, []);

    const barPositions = Array.from({ length: NUM_BARS }, (_, i) => {
        const yPos = (i - HALF_BARS) * (BAR_HEIGHT + BAR_SPACING) + Y_OFFSET;
        // const zPos = (i - HALF_BARS) * (BAR_DEPTH + BAR_SPACING);
        const zPos = i / NUM_BARS * 2
        return [0, yPos, zPos] as [number, number, number];
    });

    const requestFullScreen = (element: HTMLElement) => {
        if (element.requestFullscreen) {
            element.requestFullscreen();
        }
    };

    return (
        <Canvas
            onClick={(ev) => requestFullScreen(ev.currentTarget)}
            style={{
                cursor: 'pointer',
                // background: 'black',
            }}
        >
            <ambientLight />
            <pointLight position={[10, 10, 10]} />
            {bars.map((bar, index) => (
                <Bar
                    key={index}
                    position={barPositions[index]}
                    scale={bar.scale}
                    color={bar.color}
                />
            ))}
            <RotatingCamera />
        </Canvas>
    );
};

export default AudioVisualizerCanvas;
